const ORDER_STATUS = {
  CREATED: 'CREATED',
  PACKED: 'PACKED',
  COMPLETED: 'COMPLETED'
};

const ITEM_STATUS = {
  SENT: 'SENT',
  KEPT: 'KEPT',
  RETURNED: 'RETURNED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTIAL: 'PARTIAL',
  FAILED: 'FAILED'
};

module.exports = { ORDER_STATUS, ITEM_STATUS, PAYMENT_STATUS };